build:
  source:
    osm: "./data/saarland.pbf"
    gtfs: "./data/gtfs"
  profiles:
    driving-car-ch:
      type: "driving"
      vehicle: "car"
      metric: "fastest"
      preparation:
        contraction: true
    driving-car-overlay:
      type: "cycling"
      vehicle: "bike"
      metric: "fastest"
      preparation:
        overlay: true
        max-nodes-per-cell: 100
        overlay-method: "clique"
    public-transit:
      type: "transit"
      vehicle: "öpnv"
      preparation:
        filter-polygon: "./data/berlin.json"
        max-transfer-range: 900
build-graphs: false
services:
